services:
  simulator:
    image: ghcr.io/${OWNER:-cpe-4irc-eyjafjallajokull}/simulation-vehicles-standalone:${IMAGE_TAG:-latest}
    container_name: simulation-vehicles-standalone
    networks:
      - proxy
      - databases
    environment:
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER:-http://localhost:8080/realms/sdmis}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_TIMEOUT_MS=${KEYCLOAK_TIMEOUT_MS:-3000}
      - KEYCLOAK_TOKEN_EXPIRY_SKEW_SECONDS=${KEYCLOAK_TOKEN_EXPIRY_SKEW_SECONDS:-30}
      - SDMIS_API_BASE_URL=${SDMIS_API_BASE_URL:-http://localhost:3001}
      - SDMIS_API_TIMEOUT_MS=${SDMIS_API_TIMEOUT_MS:-5000}
      - RABBITMQ_DSN=${RABBITMQ_DSN}
      - RABBITMQ_QUEUE_TELEMETRY=${RABBITMQ_QUEUE_TELEMETRY:-vehicle_telemetry}
      - RABBITMQ_QUEUE_ASSIGNMENTS=${RABBITMQ_QUEUE_ASSIGNMENTS:-vehicle_assignments}
      - RABBITMQ_QUEUE_INCIDENT_TELEMETRY=${RABBITMQ_QUEUE_INCIDENT_TELEMETRY:-incident_telemetry}
      - RABBITMQ_EVENT_POSITION=${RABBITMQ_EVENT_POSITION:-vehicle_position_update}
      - RABBITMQ_EVENT_VEHICLE_STATUS=${RABBITMQ_EVENT_VEHICLE_STATUS:-vehicle_status_update}
      - RABBITMQ_EVENT_INCIDENT_STATUS=${RABBITMQ_EVENT_INCIDENT_STATUS:-incident_status_update}
      - RABBITMQ_EVENT_ASSIGNMENT=${RABBITMQ_EVENT_ASSIGNMENT:-vehicle_assignment}
      - RETRY_SLEEP=${RETRY_SLEEP:-1.0}
      - SIM_TICK_MS=${SIM_TICK_MS:-200}
      - VEHICLE_SPEED_MPS=${VEHICLE_SPEED_MPS:-16.67}
      - POSITION_EPSILON_METERS=${POSITION_EPSILON_METERS:-20.0}
      - TELEMETRY_BASE_SEND_INTERVAL_MS=${TELEMETRY_BASE_SEND_INTERVAL_MS:-30000}
      - TELEMETRY_MOVING_SEND_INTERVAL_MS=${TELEMETRY_MOVING_SEND_INTERVAL_MS:-1000}
      - TELEMETRY_STATUS_SEND_INTERVAL_MS=${TELEMETRY_STATUS_SEND_INTERVAL_MS:-5000}
      - TELEMETRY_LOG_PUBLISHES=${TELEMETRY_LOG_PUBLISHES:-false}
      - ROUTE_SNAP_START=${ROUTE_SNAP_START:-true}
      - ON_SITE_DURATION_MS=${ON_SITE_DURATION_MS:-60000}
    restart: unless-stopped
